name: Q1

on:
  push:
    branches:
      - main

jobs:
  create-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Vérifiez le dépôt (clone le dépôt sur l'instance de runner)
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Créez un fichier Q1_archive_README.md contenant le contenu de README.md
    - name: Create Q1_archive_README.md
      run: |
        cp README.md Q1_archive_README.md

    # 3. Configurez Git
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # 4. Ajoutez et poussez le fichier
    - name: Commit and push changes
      run: |
        git add Q1_archive_README.md
        git commit -m "Add Q1_archive_README.md"
        git push
