name: Q3

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

jobs:
  create-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Récupère le contenu de Q3.java depuis le dépôt
      - name: Create Q3_archive_java.txt with content from Q3.java
        run: |
          # Vérifie si Q3.java existe dans le dépôt
          if [ -f Q3.java ]; then
            echo "Nom et prénom : Louis Hagues" > Q3_archive_java.txt
            echo "\n--- Contenu de Q3.java ---\n" >> Q3_archive_java.txt
            cat Q3.java >> Q3_archive_java.txt  # Récupère le contenu de Q3.java et l'ajoute à Q3_archive_java.txt
          else
            echo "Erreur : Q3.java n'a pas été trouvé dans le dépôt." > Q3_archive_java.txt
          fi

      # 3. Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "Louis-Hagues"
          git config --global user.email "louis.hagues@gmail.com"

      # 4. Ajoute et pousse le fichier Q3_archive_java.txt
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Q3_archive_java.txt
          git commit -m "Add Q3_archive_java.txt"
          git push origin main
