name: Q3

permissions:
  contents: write

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

jobs:
  create-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Crée un fichier Q3.java
      - name: Create Q3.java
        run: |
          cat <<EOL > Q3.java
           public class Q3 {

              public static void main(String[] args) {
                String ligne = "";
                int nbetoile = Integer.parseInt(args[0]);
                for (int i = 0; i < nbetoile; i++) {
                  ligne += "*";
                }
                System.out.println(ligne);
              }
            }
          EOL
          
      # 3. Crée un fichier Q3_archive_java.txt avec votre nom et prénom et le contenu de Q3.java
      - name: Create Q3_archive_java.txt
        run: |
          echo "Nom et prénom : Louis-Hagues" > Q3_archive_java.txt
          echo "\n--- Contenu de Q3.java ---\n" >> Q3_archive_java.txt
          cat Q3.java >> Q3_archive_java.txt

      # 4. Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "Louis-Hagues"
          git config --global user.email "louis.hagues@gmail.com"

      # 5. Ajoute et pousse le fichier Q3_archive_java.txt
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add Q3.java Q3_archive_java.txt
          git commit -m "Add Q3.java and Q3_archive_java.txt"
          git push origin master
