name: Q4

permissions:
  contents: write

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

jobs:
  create-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Crée le fichier Q4.java
      - name: Create Q3_archive_java.txt with content from Q3.java
        run: |
          # Vérifie si Q3.java existe dans le dépôt
          if [ -f Q4.java ]; then
            echo "Nom et prénom : Louis Hagues" > Q4_archive_java.txt
            echo "\n--- Contenu de Q3.java ---\n" >> Q4_archive_java.txt
            cat Q4.java >> Q4_archive_java.txt  # Récupère le contenu de Q4.java et l'ajoute à Q4_archive_java.txt
          else
            echo "Erreur : Q4.java n'a pas été trouvé dans le dépôt." > Q4_archive_java.txt
          fi

      # 3. Obtenez la date actuelle et formatez-la au format JJ-MM-AAAA
      - name: Get current date
        id: date
        run: |
          # Date au format JJ-MM-AAAA
          DATE=$(date +'%d-%m-%Y')
          echo "DATE=$DATE" >> $GITHUB_ENV

      # 4. Crée le fichier Q4_archive_date.txt avec votre nom, prénom et le contenu du fichier Q4.java
      - name: Create Q4_archive_${{ env.DATE }}.txt
        run: |
          FILENAME="Q4_archive_${{ env.DATE }}.txt"
          echo "Nom et prénom : Louis-Hagues" > $FILENAME
          echo "\n--- Contenu de Q4.java ---\n" >> $FILENAME
          cat Q4.java >> $FILENAME

      # 5. Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "Louis-Hagues"
          git config --global user.email "louis.hagues@gmail.com"

      # 6. Effectuer un pull pour récupérer les dernières modifications
      - name: Pull latest changes from the remote repository
        run: |
          git pull origin master

      # 7. Ajoute et pousse le fichier créé
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add "Q4_archive_${{ env.DATE }}.txt"
          git commit -m "Add Q4_archive_${{ env.DATE }}.txt"
          git push origin master
